<?php

/**
 * @file
 * Contains advertising.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function advertising_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the advertising module.
    case 'help.page.advertising':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('used to generate advertising units') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function advertising_theme() {
  return [
    'advertising' => [
      'render element' => 'children',
    ],
    'advertising_image' => [
      'variables' => [
        'width' => NULL,
        'height' => NULL,
        'url' => NULL,
        'path' => NULL,
        'modal' => NULL,
        'campana' => NULL,
        'name' => NULL,
        'localization' => NULL,
      ],
    ],
    'advertising_video' => [
      'variables' => [
        'width' => NULL,
        'height' => NULL,
        'src' => NULL,
        'title' => NULL,
        'modal' => NULL,
        'campana' => NULL,
        'name' => NULL,
        'localization' => NULL,
      ],
    ],
    'advertising_html' => [
      'variables' => [
        'width' => NULL,
        'height' => NULL,
        'body' => NULL,
        'modal' => NULL,
        'campana' => NULL,
        'name' => NULL,
        'localization' => NULL,
      ],
    ],
    'advertising_superior' => [
      'variables' => [
        'body' => NULL,
        'path' => NULL,
        'button' => NULL,
        'campana' => NULL,
        'name' => NULL,
        'localization' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_views_data().
 */
function advertising_views_data() {
  $data['views']['table']['group'] = t('Custom Global');
  $data['views']['table']['join'] = [
    // #global is a special flag which allows a table to appear all the time.
    '#global' => [],
  ];

  $data['views']['campana_active'] = [
    'title' => t('Active advertising'),
    'help' => t('Advertisign campana active'),
    'field' => [
      'id' => 'campana_active',
    ],
  ];
  $data['views']['campana_start_and_end_date'] = [
    'title' => t('Start and End date - Advertisign'),
    'filter' => [
      'title' => t('Start and End date - Advertisign'),
      'field' => 'id',
      'id' => 'camapana_start_and_end_date',
    ],
  ];
  return $data;
}
