
# Product entity menu items definition
entity.product_entity.collection:
  title: 'Product entity list'
  route_name: entity.product_entity.collection
  description: 'List Product entity entities'
  parent: system.admin_structure

product_entity.admin.structure.settings:
  title: 'Product entity settings'
  description: 'Configure Product entity entities'
  route_name: product_entity.settings
  parent: system.admin_structure
  weight: 100
